### ISSUE TITLE
Accidental /kill used

### ISSUE THREAD

**Issue by boredcoder411** [KawaMood/waystones_v3#1]
I accidentally use /kill @e[type=#!minecraft:arrows] instead of /kill @e[type=#minecraft:arrows] and it removed the waystones. I already removed the leftover entities using the function provided. I re-placed the waystones I killed, but the interface still shows the dead waystones. How can I reset the list of placed waystones?

**Comment by KawaMood** [comment]
Hi, please rather use the Discord server to ask for issues. I don't often check my mail on this account.
There is a command for this context, it will recreate all waystones from the database:/function pk_waystones:base/debug/recreate_all_waystones/start ______________________________________________________________________________

KawaMood - www.kawamood.com
Youtube | Planet Minecraft | Discord | Twitter

Le Jeudi, Mars 21, 2024 19:48 CET, boredcoder411 ***@***.***> a écrit:
 
 
I accidentally use /kill @e[type=#!minecraft:arrows] instead of /kill @e[type=#minecraft:arrows] and it removed the waystones. I already removed the leftover entities using the function provided. I re-placed the waystones I killed, but the interface still shows the dead waystones. How can I reset the list of placed waystones?

**Comment by boredcoder411** [comment]
I just saw the commits adding this, thank you!
